name: "Set Secret"
author: "action-pack"
description: "Action to set repository secrets"

branding:
  icon: "lock"
  color: "gray-dark"

inputs:
  name:
    description: Secret name
    required: true

  value:
    description: Secret value
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Owner of repository
    default: false
    required: false

  org:
    description: Flag for organization
    default: false
    required: false

  token:
    description: Repository access token
    required: true

runs:
  using: 'node18'
  main: 'dist/index.js'
