name: Test

on: 
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Test action
        uses: action-pack/set-secret@v1
        with:
          name: 'TEST'
          value: 'TEST'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
